// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var Holepunch = exports.Holepunch = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Message = exports.Message = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineHolepunch()
defineMessage()

function defineHolepunch () {
  var enc = [
    encodings.bytes
  ]

  Holepunch.encodingLength = encodingLength
  Holepunch.encode = encode
  Holepunch.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.from)) {
      var len = enc[0].encodingLength(obj.from)
      length += 1 + len
    }
    if (defined(obj.to)) {
      var len = enc[0].encodingLength(obj.to)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.from)) {
      buf[offset++] = 18
      enc[0].encode(obj.from, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.to)) {
      buf[offset++] = 26
      enc[0].encode(obj.to, buf, offset)
      offset += enc[0].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      from: null,
      to: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 2:
        obj.from = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 3:
        obj.to = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineMessage () {
  var enc = [
    encodings.varint,
    encodings.bytes,
    encodings.string
  ]

  Message.encodingLength = encodingLength
  Message.encode = encode
  Message.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.rid)) throw new Error("rid is required")
    var len = enc[0].encodingLength(obj.rid)
    length += 1 + len
    if (defined(obj.id)) {
      var len = enc[1].encodingLength(obj.id)
      length += 1 + len
    }
    if (defined(obj.target)) {
      var len = enc[1].encodingLength(obj.target)
      length += 1 + len
    }
    if (defined(obj.closerNodes)) {
      var len = enc[1].encodingLength(obj.closerNodes)
      length += 1 + len
    }
    if (defined(obj.roundtripToken)) {
      var len = enc[1].encodingLength(obj.roundtripToken)
      length += 1 + len
    }
    if (defined(obj.command)) {
      var len = enc[2].encodingLength(obj.command)
      length += 1 + len
    }
    if (defined(obj.error)) {
      var len = enc[2].encodingLength(obj.error)
      length += 1 + len
    }
    if (defined(obj.value)) {
      var len = enc[1].encodingLength(obj.value)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.rid)) throw new Error("rid is required")
    buf[offset++] = 8
    enc[0].encode(obj.rid, buf, offset)
    offset += enc[0].encode.bytes
    if (defined(obj.id)) {
      buf[offset++] = 18
      enc[1].encode(obj.id, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.target)) {
      buf[offset++] = 26
      enc[1].encode(obj.target, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.closerNodes)) {
      buf[offset++] = 34
      enc[1].encode(obj.closerNodes, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.roundtripToken)) {
      buf[offset++] = 42
      enc[1].encode(obj.roundtripToken, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.command)) {
      buf[offset++] = 50
      enc[2].encode(obj.command, buf, offset)
      offset += enc[2].encode.bytes
    }
    if (defined(obj.error)) {
      buf[offset++] = 58
      enc[2].encode(obj.error, buf, offset)
      offset += enc[2].encode.bytes
    }
    if (defined(obj.value)) {
      buf[offset++] = 66
      enc[1].encode(obj.value, buf, offset)
      offset += enc[1].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      rid: 0,
      id: null,
      target: null,
      closerNodes: null,
      roundtripToken: null,
      command: "",
      error: "",
      value: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.rid = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        case 2:
        obj.id = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 3:
        obj.target = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 4:
        obj.closerNodes = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 5:
        obj.roundtripToken = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 6:
        obj.command = enc[2].decode(buf, offset)
        offset += enc[2].decode.bytes
        break
        case 7:
        obj.error = enc[2].decode(buf, offset)
        offset += enc[2].decode.bytes
        break
        case 8:
        obj.value = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
